		<div id="institutional">
			<h2>Institucional</h2>
			<p>{$paragraph1}Com a necessidade de tornar mais eficiente e eficaz o serviço público, a E&L Produções de Software, fundada em agosto de 1993, em Domingos Martins – ES, começou a desenvolver sistemas informatizados que apresentassem o que há de melhor em Tecnologia da Informação e Comunicação (TIC), de acordo com as exigências legais necessárias à administração pública. </p>
			<br>
			<p>{$paragraph2}Hoje, com uma experiência de mais de 20 anos de mercado, a E&L tornou-se uma empresa especializada no setor de soluções em Tecnologia da Informação e Comunicação. Possuímos clientes em vários Estados do país, tais como: ES, RJ, MG e BA oferecendo sistemas integrados de gestão pública, entre eles: Tributário, Frotas, Recursos Humanos, Saúde, Contabilidade, Almoxarifado, Patrimônio, Compras, Protocolo, Educação entre outros. Dentre nossos clientes estão: Prefeituras, Câmaras, Institutos e/ ou Fundações Previdenciárias Municipais, Secretarias de Estado, Instituições de Ensino e Assembléias Legislativas.</p>
			<br>
			<p>{$paragraph3}Além de comercializar esses produtos, a E&L oferece todo o suporte técnico (local ou por telefone) para instalação, manutenção e atualização dos sistemas, e ainda oferece treinamento para que seus clientes (usuários) possam executar da melhor forma possível todos os inúmeros recursos e vantagens que o software oferece.</p>
			<br>
			<p>{$paragraph4}Em dezembro de 2005 conquistou o certificado na NBR ISO 9001:2000 (Sistema de Gestão da Qualidade SGQ) que garante a melhoria contínua de seus processos e foi recertificada na NBR ISO 9001:2008. Com a manutenção do SGQ obteve, em junho de 2010, o certificado SGQ-TEC (programa de qualificação e certificação de empresas de tecnologia da informação). Em março de 2008, foi aprovada como uma empresa qualificada no desenvolvimento de software, pelo Programa Nacional de Apoio Gestão Administrativa e Fiscal dos Municípios Brasileiros PNAFM. Em 2012 foi certificada no MPS.Br (Melhoria de Processos do Software Brasileiro) no nível G e atualmente está buscando a certificação no nível F.</p>
			<br>
			<p>{$paragraph5}A nossa atuação socioambiental é realizada por meio de doações periódicas (em espécie ou material) a entidades carentes e a escolas e nossa empresa é considerada uma empresa de produção limpa, pois não poluímos e nem geramos impactos ambientais, ou seja, nos desenvolvemos ajudando a nossa comunidade a crescer e mantemos o nosso compromisso de preservação do meio ambiente – da natureza.</p>
		</div>